version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data  # Asumiendo que tu aplicación almacena la base de datos en un directorio `data`
